name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted # Specify the self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: sudo docker build -t octagon-backend:latest .

      - name: Stop existing containers
        run: |
          docker ps -q -f "name=octagon-backend" | xargs -r docker stop
          docker ps -aq -f "name=octagon-backend" | xargs -r docker rm

      - name: Build and run new container
        run: |
          docker build -t octagon-backend:latest .
          docker run -d --rm --name octagon-backend -p 8080:8080 octagon-backend:latest
